baseURL = "https://yukimori1223.github.io/"
languageCode = "ja-ja"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    name = "yukimori1223"
    title = "My portal"
    author = "Yuki Mori"
    description = "Yuki Mor's portal"
    copyright = "Yuki Mori, 2022"
    theme = "light" # `dark` or `light`
    useResources = false

    # Profile section
    [params.profile]
        name = "Yuki Mori"
        photo = "images/profile.png"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/YukiMori1223?tab=repositories"
        title = "GitHub"
		
		[[params.social.list]]
        icon = "ai ai-google-scholar"
        url = "https://scholar.google.com/citations?user=ickwiRwAAAAJ&hl=ja"
        title = "Google Scholar"
						
		[[params.social.list]]
        icon = "fab fa-twitter"
        url = "#"
        title = "Twitter"
		

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Doctor of engineering"
        college = "The University of Tokyo"
        dates = "2021"
        thesis_title = "Development of the numerical model for the multiscale numerical simulation in the solid-fluid multiphase flow"
        thesis_link = "#"

        [[params.education.list]]
        degree = "Master of engineering"
        college = "The University of Tokyo"
        dates = "2017"
        thesis_title = "Development and application of an Euler-Lagrange method for industrial multi-phase flows"
        thesis_link = "#"

        [[params.education.list]]
        degree = "Bachelor of engineering"
        college = "The University of Tokyo"
        dates = "2019"
		thesis_title = "Development of a visualization technique for a large-scale DEM simulation"
        thesis_link = "#"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Make movies"

        [[params.hobbies.list]]
        interest = "Watch movies"
		
        [[params.hobbies.list]]
        interest = "Make games"
	
	    [[params.hobbies.list]]
        interest = "Play games"

    [params.aboutme]
        description = "This is me."

    # Experiences section
    [params.experiences]
        title = "Experiences"

        [[params.jobs.list]]
        position = "Researcher"
        dates = "2022 - *Present*"
		link = "#"
        company = "Toyota central R&D labs., Inc."
		details =""

       
    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "Project Eula"
        url = "https://github.com/YukiMori1223/Eula"
        description = "Eularian-Lagrangean solver"
		
		[[params.projects.list]]
        title = "数学に関する個人的まとめ"
        url = "https://github.com/YukiMori1223/Math_Book"
        description = "数学に関する個人的まとめ"
		
		[[params.projects.list]]
        title = "プログラムに関する個人的まとめ"
        url = "https://github.com/YukiMori1223/Program_Book"
        description = "プログラムに関する個人的まとめ"
		
		[[params.projects.list]]
        title = "Blenderに関する個人的まとめ"
        url = "#"
        description = "Blenderに関する個人的まとめ"
		
		[[params.projects.list]]
        title = "個人的LaTeXテンプレート"
        url = "https://github.com/YukiMori1223/Template_Book"
        description = "個人的LaTeXテンプレート"

    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "C++"
        skillrating = 60
                
        [[params.skills.list]]
        skill = "Python"
        skillrating = 40
		
        [[params.skills.list]]
        skill = "Blender"
        skillrating = 80
		
		[[params.skills.list]]
        skill = "Adobe After Effects"
        skillrating = 90
		
		[[params.skills.list]]
        skill = "Unity"
        skillrating = 50
